### PR TITLE
Relax vitest peerDependency

### LINKED ISSUE #5: Fix vitest peerDependency
The current setting
```
"peerDependencies": {
   "vitest": "^0.31.0"
}
```
does not allow upgrading to vitest 0.32 .

You can test this here https://semver.npmjs.com/ . `^0.31.0` will not list 0.32

### PR DESCRIPTION
**Pull request by Kamahl19**
close #5

### CODE REVIEW

**Comment by Kamahl19** [comment]
@chaance would you please take a look on this? Thanks!

**Comment by Kamahl19** [comment]
@chaance could you please merge this? Thanks a lot!

**Comment by mutoe** [comment]
Did the author forget about it?

**Comment by chaance** [comment]
The author is busy. Happy to merge but I have a few other changes lined up before I cut a new release.

**Pull request merged**
